FRUITS = [
    'açaí',
    'apple',
    'apricot',
    'avocado',
    'banana',
    'betel nut',
    'bilberry',
    'black cherry',
    'blackberry',
    'blood orange',
    'breadfruit',
    'calamansi',
    'cantaloupe',
    'cherry',
    'cranberry',
    'coconut',
    'custard apple',
    'damson',
    'date',
    'dragonfruit',
    'durian',
    'fig',
    'goji berry',
    'gooseberry',
    'grape',
    'grapefruit',
    'greengage',
    'guava',
    'hawthorn',
    'kaffir lime',
    'kiwi',
    'kumquat',
    'lemon',
    'lime',
    'lingonberry',
    'loganberry',
    'lychee',
    'mandarin',
    'mango',
    'mangosteen',
    'melon',
    'nectarine',
    'orange',
    'papaya',
    'passion fruit',
    'peach',
    'pear',
    'pineapple',
    'plum',
    'pomegranate',
    'pomelo',
    'prickly pear',
    'quince',
    'rambutan',
    'raspberry',
    'sea buckthorn',
    'sloe',
    'spanish lime',
    'starfruit',
    'strawberry',
    'tamarind',
    'tangerine',
    'watermelon'
]
